// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3eaf2be5-e037-402f-b955-e1eb7b1a5cde",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OL23MSEIl",
    "aws_user_pools_web_client_id": "62up68l3cev3tflubqq529f60n",
    "oauth": {}
};


export default awsmobile;
